/*
 * Copyright (c) 2023 pihta24 <admin@pihta24.ru>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package ru.pihta24.achievementplugin.utils

object DefaultConfig {
    val Advancements = mapOf(
        "story/mine_stone" to "Stone Age",
        "story/upgrade_tools" to "Getting an Upgrade",
        "story/smelt_iron" to "Acquire Hardware",
        "story/obtain_armor" to "Suit Up",
        "story/lava_bucket" to "Hot Stuff",
        "story/iron_tools" to "Isn't It Iron Pick",
        "story/deflect_arrow" to "Not Today, Thank You",
        "story/form_obsidian" to "Ice Bucket Challenge",
        "story/mine_diamond" to "Diamonds!",
        "story/enter_the_nether" to "We Need to Go Deeper",
        "story/shiny_gear" to "Cover Me with Diamonds",
        "story/enchant_item" to "Enchanter",
        "story/cure_zombie_villager" to "Zombie Doctor",
        "story/follow_ender_eye" to "Eye Spy",
        "story/enter_the_end" to "The End?",
        "nether/return_to_sender" to "Return to Sender",
        "nether/find_bastion" to "Those Were the Days",
        "nether/obtain_ancient_debris" to "Hidden in the Depths",
        "nether/fast_travel" to "Subspace Bubble",
        "nether/find_fortress" to "A Terrible Fortress",
        "nether/obtain_crying_obsidian" to "Who is Cutting Onions?",
        "nether/distract_piglin" to "Oh Shiny",
        "nether/ride_strider" to "This Boat Has Legs",
        "nether/uneasy_alliance" to "Uneasy Alliance",
        "nether/loot_bastion" to "War Pigs",
        "nether/use_lodestone" to "Country Lode, Take Me Home",
        "nether/netherite_armor" to "Cover Me in Debris",
        "nether/get_wither_skull" to "Spooky Scary Skeleton",
        "nether/obtain_blaze_rod" to "Into Fire",
        "nether/charge_respawn_anchor" to "Not Quite \"Nine\" Lives",
        "nether/ride_strider_in_overworld_lava" to "Feels Like Home",
        "nether/explore_nether" to "Hot Tourist Destinations",
        "nether/summon_wither" to "Withering Heights",
        "nether/brew_potion" to "Local Brewery",
        "nether/create_beacon" to "Bring Home the Beacon",
        "nether/all_potions" to "A Furious Cocktail",
        "nether/create_full_beacon" to "Beaconator",
        "nether/all_effects" to "How Did We Get Here?",
        "end/kill_dragon" to "Free the End",
        "end/dragon_egg" to "The Next Generation",
        "end/enter_end_gateway" to "Remote Getaway",
        "end/respawn_dragon" to "The End... Again...",
        "end/dragon_breath" to "You Need a Mint",
        "end/find_end_city" to "The City at the End of the Game",
        "end/elytra" to "Sky's the Limit",
        "end/levitate" to "Great View From Up Here",
        "adventure/voluntary_exile" to "Voluntary Exile",
        "adventure/spyglass_at_parrot" to "Is It a Bird?",
        "adventure/kill_a_mob" to "Monster Hunter",
        "adventure/read_power_of_chiseled_bookshelf" to "The Power of Books",
        "adventure/trade" to "What a Deal!",
        "adventure/trim_with_any_armor_pattern" to "Crafting a New Look",
        "adventure/honey_block_slide" to "Sticky Situation",
        "adventure/ol_betsy" to "Ol' Betsy",
        "adventure/lightning_rod_with_villager_no_fire" to "Surge Protector",
        "adventure/fall_from_world_height" to "Caves & Cliffs",
        "adventure/salvage_sherd" to "Respecting the Remnants",
        "adventure/avoid_vibration" to "Sneak 100",
        "adventure/sleep_in_bed" to "Sweet Dreams",
        "adventure/hero_of_the_village" to "Hero of the Village",
        "adventure/spyglass_at_ghast" to "Is It a Balloon?",
        "adventure/throw_trident" to "A Throwaway Joke",
        "adventure/kill_mob_near_sculk_catalyst" to "It Spreads",
        "adventure/shoot_arrow" to "Take Aim",
        "adventure/kill_all_mobs" to "Monsters Hunted",
        "adventure/totem_of_undying" to "Postmortal",
        "adventure/summon_iron_golem" to "Hired Help",
        "adventure/trade_at_world_height" to "Star Trader",
        "adventure/trim_with_all_exclusive_armor_patterns" to "Smithing with Style",
        "adventure/two_birds_one_arrow" to "Two Birds, One Arrow",
        "adventure/whos_the_pillager_now" to "Who's the Pillager Now?",
        "adventure/arbalistic" to "Arbalistic",
        "adventure/craft_decorated_pot_using_only_sherds" to "Careful Restoration",
        "adventure/adventuring_time" to "Adventuring Time",
        "adventure/play_jukebox_in_meadows" to "Sound of Music",
        "adventure/walk_on_powder_snow_with_leather_boots" to "Light as a Rabbit",
        "adventure/spyglass_at_dragon" to "Is It a Plane?",
        "adventure/very_very_frightening" to "Very Very Frightening",
        "adventure/sniper_duel" to "Sniper Duel",
        "adventure/bullseye" to "Bullseye",
        "husbandry/safely_harvest_honey" to "Bee Our Guest",
        "husbandry/breed_an_animal" to "The Parrots and the Bats",
        "husbandry/allay_deliver_item_to_player" to "You've Got a Friend in Me",
        "husbandry/ride_a_boat_with_a_goat" to "Whatever Floats Your Goat!",
        "husbandry/tame_an_animal" to "Best Friends Forever",
        "husbandry/make_a_sign_glow" to "Glow and Behold!",
        "husbandry/fishy_business" to "Fishy Business",
        "husbandry/silk_touch_nest" to "Total Beelocation",
        "husbandry/tadpole_in_a_bucket" to "Bukkit Bukkit",
        "husbandry/obtain_sniffer_egg" to "Smells Interesting",
        "husbandry/plant_seed" to "A Seedy Place",
        "husbandry/wax_on" to "Wax On",
        "husbandry/bred_all_animals" to "Two by Two",
        "husbandry/allay_deliver_cake_to_note_block" to "Birthday Song",
        "husbandry/complete_catalogue" to "A Complete Catalogue",
        "husbandry/tactical_fishing" to "Tactical Fishing",
        "husbandry/leash_all_frog_variants" to "When the Squad Hops into Town",
        "husbandry/feed_snifflet" to "Little Sniffs",
        "husbandry/balanced_diet" to "A Balanced Diet",
        "husbandry/obtain_netherite_hoe" to "Serious Dedication",
        "husbandry/wax_off" to "Wax Off",
        "husbandry/axolotl_in_a_bucket" to "The Cutest Predator",
        "husbandry/froglights" to "With Our Powers Combined!",
        "husbandry/kill_axolotl_target" to "The Healing Power of Friendship!",
        "husbandry/plant_any_sniffer_seed" to "Planting the Past"
    )

    val Weights = mapOf(
        "story/mine_stone" to 100,
        "story/upgrade_tools" to 200,
        "story/smelt_iron" to 200,
        "story/obtain_armor" to 250,
        "story/lava_bucket" to 300,
        "story/iron_tools" to 250,
        "story/deflect_arrow" to 100,
        "story/form_obsidian" to 50,
        "story/mine_diamond" to 100,
        "story/enter_the_nether" to 100,
        "story/shiny_gear" to 50,
        "story/enchant_item" to 20,
        "story/cure_zombie_villager" to 0,
        "story/follow_ender_eye" to 0,
        "story/enter_the_end" to 0,
        "nether/return_to_sender" to 20,
        "nether/find_bastion" to 30,
        "nether/obtain_ancient_debris" to 10,
        "nether/fast_travel" to 0,
        "nether/find_fortress" to 30,
        "nether/obtain_crying_obsidian" to 25,
        "nether/distract_piglin" to 25,
        "nether/ride_strider" to 1,
        "nether/uneasy_alliance" to 0,
        "nether/loot_bastion" to 30,
        "nether/use_lodestone" to 0,
        "nether/netherite_armor" to 0,
        "nether/get_wither_skull" to 0,
        "nether/obtain_blaze_rod" to 10,
        "nether/charge_respawn_anchor" to 10,
        "nether/ride_strider_in_overworld_lava" to 0,
        "nether/explore_nether" to 1,
        "nether/summon_wither" to 0,
        "nether/brew_potion" to 5,
        "nether/create_beacon" to 0,
        "nether/all_potions" to 0,
        "nether/create_full_beacon" to 0,
        "nether/all_effects" to 0,
        "end/kill_dragon" to 0,
        "end/dragon_egg" to 0,
        "end/enter_end_gateway" to 0,
        "end/respawn_dragon" to 0,
        "end/dragon_breath" to 0,
        "end/find_end_city" to 0,
        "end/elytra" to 0,
        "end/levitate" to 0,
        "adventure/voluntary_exile" to 7,
        "adventure/spyglass_at_parrot" to 1,
        "adventure/kill_a_mob" to 300,
        "adventure/read_power_of_chiseled_bookshelf" to 0,
        "adventure/trade" to 50,
        "adventure/trim_with_any_armor_pattern" to 0,
        "adventure/honey_block_slide" to 0,
        "adventure/ol_betsy" to 25,
        "adventure/lightning_rod_with_villager_no_fire" to 0,
        "adventure/fall_from_world_height" to 1,
        "adventure/salvage_sherd" to 0,
        "adventure/avoid_vibration" to 1,
        "adventure/sleep_in_bed" to 5,
        "adventure/hero_of_the_village" to 0,
        "adventure/spyglass_at_ghast" to 1,
        "adventure/throw_trident" to 0,
        "adventure/kill_mob_near_sculk_catalyst" to 1,
        "adventure/shoot_arrow" to 50,
        "adventure/kill_all_mobs" to 0,
        "adventure/totem_of_undying" to 0,
        "adventure/summon_iron_golem" to 0,
        "adventure/trade_at_world_height" to 0,
        "adventure/trim_with_all_exclusive_armor_patterns" to 0,
        "adventure/two_birds_one_arrow" to 0,
        "adventure/whos_the_pillager_now" to 1,
        "adventure/arbalistic" to 0,
        "adventure/craft_decorated_pot_using_only_sherds" to 0,
        "adventure/adventuring_time" to 0,
        "adventure/play_jukebox_in_meadows" to 0,
        "adventure/walk_on_powder_snow_with_leather_boots" to 10,
        "adventure/spyglass_at_dragon" to 0,
        "adventure/very_very_frightening" to 0,
        "adventure/sniper_duel" to 0,
        "adventure/bullseye" to 1,
        "husbandry/safely_harvest_honey" to 1,
        "husbandry/breed_an_animal" to 100,
        "husbandry/allay_deliver_item_to_player" to 0,
        "husbandry/ride_a_boat_with_a_goat" to 0,
        "husbandry/tame_an_animal" to 70,
        "husbandry/make_a_sign_glow" to 60,
        "husbandry/fishy_business" to 60,
        "husbandry/silk_touch_nest" to 0,
        "husbandry/tadpole_in_a_bucket" to 0,
        "husbandry/obtain_sniffer_egg" to 0,
        "husbandry/plant_seed" to 100,
        "husbandry/wax_on" to 0,
        "husbandry/bred_all_animals" to 0,
        "husbandry/allay_deliver_cake_to_note_block" to 0,
        "husbandry/complete_catalogue" to 0,
        "husbandry/tactical_fishing" to 100,
        "husbandry/leash_all_frog_variants" to 0,
        "husbandry/feed_snifflet" to 0,
        "husbandry/balanced_diet" to 0,
        "husbandry/obtain_netherite_hoe" to 0,
        "husbandry/wax_off" to 0,
        "husbandry/axolotl_in_a_bucket" to 10,
        "husbandry/froglights" to 0,
        "husbandry/kill_axolotl_target" to 0,
        "husbandry/plant_any_sniffer_seed" to 0
    )

    val goalsDefaults = Weights.map {
        mapOf(
            "key" to it.key,
            "name" to Advancements.getOrDefault(it.key, ""),
            "weight" to it.value,
            "description" to ""
        )
    }
}